apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
  name: cert-manager-test
spec:
  ingressClassName: nginx
  rules:
  - host: navidrome.fuckamazon.org
    http:
      paths:
      - backend:
          service:
            name: navidrome
            port:
              number: 4533
        path: /navidrome
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - navidrome.fuckamazon.org
    secretName: navidrome-fuckamazon-org-tls
